version: "2.2"

services:
  license:
    build:
      context: .
      dockerfile: license/Dockerfile.license
    image: age-license:15.0
    hostname: license.age-docker-cluster_default
    container_name: age-license
    expose:
      - "6200"
    volumes:
      - ./age.dat:/license/age.dat
    mac_address: de:59:34:6f:b6:98

  head:
    build:
      context: .
      dockerfile: age/Dockerfile.age
    image: age:2022.1.0  
    command: ["head-node"]
    container_name: age-head 
    hostname: head.age-docker-cluster_default
    privileged: true 
    volumes:
      - opt_age:/opt/age
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
    expose:
      - "6444"
      - "6445"
    depends_on:
      - "license"

  c1:
    image: age:2022.1.0 
    build:
      context: .
      dockerfile: age/Dockerfile.age
    command: ["compute-node"]
    hostname: c1.age-docker-cluster_default
    container_name: age-c1
    privileged: true 
    volumes:
      - opt_age:/opt/age 
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
      - opt_r:/opt/R
      - etc_rstudio:/etc/rstudio
      - usr_lib_rstudio:/usr/lib/rstudio-server
      - shared_storage:/opt/rstudio/shared
    expose:
      - "6444"
    depends_on:
      - "head"

  c2:
    image: age:2022.1.0
    build:
      context: .
      dockerfile: age/Dockerfile.age
    command: ["compute-node"]
    hostname: c2.age-docker-cluster_default
    container_name: age-c2
    privileged: true
    volumes:
      - opt_age:/opt/age
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
      - opt_r:/opt/R
      - etc_rstudio:/etc/rstudio
      - usr_lib_rstudio:/usr/lib/rstudio-server
      - shared_storage:/opt/rstudio/shared
    expose:
      - "6444"
    depends_on:
      - "head"

  rsw:
    build:
      context: . 
      dockerfile: rsw/Dockerfile.rsw
    image: rsw:2022.07.1-554.pro3
    command: ["rsw"]
    hostname: rsw.age-docker-cluster_default
    container_name: age-rsw
    privileged: true
    environment:
      RSW_LICENSE: ${RSW_LICENSE}
    volumes:
      - opt_age:/opt/age
      - home_rstudio:/home/rstudio
      - home_ageadmin:/home/ageadmin
      - opt_r:/opt/R
      - etc_rstudio:/etc/rstudio
      - usr_lib_rstudio:/usr/lib/rstudio-server
      - shared_storage:/opt/rstudio/shared
    ports:
      - "8989:8787"
    depends_on:
      - "head"


volumes:
  opt_age:
  home_ageadmin:
  home_rstudio:
  opt_r:
  etc_rstudio:
  usr_lib_rstudio:
  shared_storage:
