version: "2.2"

services:
  license:
    build:
      context: .
      dockerfile: license/Dockerfile.license
    image: age-license:15.0
    hostname: license.age_default
    container_name: age-license
    ports:
      - "6200:6200"
    volumes:
      - ./age.dat:/license/age.dat
    mac_address: de:59:34:6f:b6:98

  head:
    build:
      context: .
      dockerfile: age/Dockerfile.age
    image: age:2022.1.0  
    command: ["head-node"]
    container_name: head 
    hostname: head.age_default
    privileged: true 
    volumes:
      - opt_age:/opt/age
      - home:/home
    expose:
      - "6444"
      - "6445"
    depends_on:
      - "license"

  c1:
    image: age:2022.1.0 
    command: ["compute-node"]
    hostname: c1.age_default
    container_name: c1
    privileged: true 
    volumes:
      - opt_age:/opt/age 
      - home:/home
    expose:
      - "6444"
    depends_on:
      - "head"

  c2:
    image: age:2022.1.0
    command: ["compute-node"]
    hostname: c2.age_default
    container_name: c2
    privileged: true
    volumes:
      - opt_age:/opt/age
      - home:/home
    expose:
      - "6444"
    depends_on:
      - "c1"

volumes:
  opt_age:
  home:

