
services:


  head:
    image: age:${AGE_VERSION:-2022.1.2}
    build:
      context: .
      dockerfile: age/Dockerfile.age
      args: 
        AGE_VERSION: ${AGE_VERSION:-2022.1.2}
    command: ["head-node"]
    container_name: head 
    hostname: head.age-docker-cluster_default
    privileged: true 
    volumes:
      - opt_age:/opt/age
      - home_ageadmin:/home/ageadmin
    expose:
      - "6444"
      - "6445"

  c1:
    image: age:${AGE_VERSION:-2022.1.2} 
    build:
      context: .
      dockerfile: age/Dockerfile.age
      args: 
        AGE_VERSION: ${AGE_VERSION:-2022.1.2}
    command: ["compute-node"]
    hostname: c1.age-docker-cluster_default
    container_name: c1
    privileged: true 
    volumes:
      - opt_age:/opt/age 
      - home_ageadmin:/home/ageadmin
      - shared_storage:/opt/rstudio/shared
    expose:
      - "6444"
    depends_on:
      - "head"

  c2:
    image: age:${AGE_VERSION:-2022.1.2}
    build:
      context: .
      dockerfile: age/Dockerfile.age
      args: 
        AGE_VERSION: ${AGE_VERSION:-2022.1.2}
    command: ["compute-node"]
    hostname: c2.age-docker-cluster_default
    container_name: c2
    privileged: true
    volumes:
      - opt_age:/opt/age
      - home_ageadmin:/home/ageadmin
    expose:
      - "6444"
    depends_on:
      - "head"


volumes:
  opt_age:
  home_ageadmin:
  shared_storage:
